### ISSUE TITLE
Big Issue

### ISSUE THREAD

**Issue by KazeroG** [flarum/core#1431]
Big Issue

No Compatibilities between Ext or just big error in ...

- vendor/zurtr/flarum-ext-onesignal (https://discuss.flarum.org/u/vivex)
- vendor/ganuonglachanh/flarum-ext-sharing (https://discuss.flarum.org/u/ganuonglachanh)
- vendor/push-edx/flarum-ext-restricted-reply
- vendor/zendframework/zend-diactoros/

**Log :** 
```
Warning: Missing argument 2 for Zurtr\OneSignal\OneSignalAPI::__construct(), called in /home/u857997072/public_html/forum/v2/vendor/zurtr/flarum-ext-onesignal/src/Listener/SendWebPushNotification.php on line 21 and defined in /home/u857997072/public_html/forum/v2/vendor/zurtr/flarum-ext-onesignal/src/OneSignalAPI.php on line 9

Notice: Undefined variable: oneSignalAPIKey in /home/u857997072/public_html/forum/v2/vendor/zurtr/flarum-ext-onesignal/src/OneSignalAPI.php on line 11

Notice: Trying to get property of non-object in /home/u857997072/public_html/forum/v2/vendor/ganuonglachanh/flarum-ext-sharing/src/Listener/AddOgTags.php on line 106

Notice: Trying to get property of non-object in /home/u857997072/public_html/forum/v2/vendor/ganuonglachanh/flarum-ext-sharing/src/Listener/AddOgTags.php on line 106

Notice: Trying to get property of non-object in /home/u857997072/public_html/forum/v2/vendor/ganuonglachanh/flarum-ext-sharing/src/Listener/AddOgTags.php on line 107

Notice: Undefined index: page in /home/u857997072/public_html/forum/v2/vendor/ganuonglachanh/flarum-ext-sharing/src/Listener/AddOgTags.php on line 108

Notice: Trying to get property of non-object in /home/u857997072/public_html/forum/v2/vendor/ganuonglachanh/flarum-ext-sharing/src/Listener/AddOgTags.php on line 113

Notice: Trying to get property of non-object in /home/u857997072/public_html/forum/v2/vendor/ganuonglachanh/flarum-ext-sharing/src/Listener/AddOgTags.php on line 115

Notice: Trying to get property of non-object in /home/u857997072/public_html/forum/v2/vendor/ganuonglachanh/flarum-ext-sharing/src/Listener/AddOgTags.php on line 115

Notice: Undefined index: image in /home/u857997072/public_html/forum/v2/vendor/ganuonglachanh/flarum-ext-sharing/src/Listener/AddOgTags.php on line 131

Notice: Undefined variable: ability in /home/u857997072/public_html/forum/v2/vendor/push-edx/flarum-ext-restricted-reply/src/Access/RestrictedReplyPolicy.php on line 71

Notice: Undefined variable: ability in /home/u857997072/public_html/forum/v2/vendor/push-edx/flarum-ext-restricted-reply/src/Access/RestrictedReplyPolicy.php on line 71

Notice: Undefined variable: ability in /home/u857997072/public_html/forum/v2/vendor/push-edx/flarum-ext-restricted-reply/src/Access/RestrictedReplyPolicy.php on line 71

Notice: Undefined variable: ability in /home/u857997072/public_html/forum/v2/vendor/push-edx/flarum-ext-restricted-reply/src/Access/RestrictedReplyPolicy.php on line 71

Notice: Undefined variable: ability in /home/u857997072/public_html/forum/v2/vendor/push-edx/flarum-ext-restricted-reply/src/Access/RestrictedReplyPolicy.php on line 71

Notice: Undefined variable: ability in /home/u857997072/public_html/forum/v2/vendor/push-edx/flarum-ext-restricted-reply/src/Access/RestrictedReplyPolicy.php on line 71

Notice: Undefined variable: ability in /home/u857997072/public_html/forum/v2/vendor/push-edx/flarum-ext-restricted-reply/src/Access/RestrictedReplyPolicy.php on line 71

Notice: Undefined variable: ability in /home/u857997072/public_html/forum/v2/vendor/push-edx/flarum-ext-restricted-reply/src/Access/RestrictedReplyPolicy.php on line 71

Notice: Undefined variable: ability in /home/u857997072/public_html/forum/v2/vendor/push-edx/flarum-ext-restricted-reply/src/Access/RestrictedReplyPolicy.php on line 71

Notice: Undefined variable: ability in /home/u857997072/public_html/forum/v2/vendor/push-edx/flarum-ext-restricted-reply/src/Access/RestrictedReplyPolicy.php on line 71

Notice: Undefined variable: ability in /home/u857997072/public_html/forum/v2/vendor/push-edx/flarum-ext-restricted-reply/src/Access/RestrictedReplyPolicy.php on line 71

Notice: Undefined variable: ability in /home/u857997072/public_html/forum/v2/vendor/push-edx/flarum-ext-restricted-reply/src/Access/RestrictedReplyPolicy.php on line 71

Notice: Undefined variable: ability in /home/u857997072/public_html/forum/v2/vendor/push-edx/flarum-ext-restricted-reply/src/Access/RestrictedReplyPolicy.php on line 71

Notice: Undefined variable: ability in /home/u857997072/public_html/forum/v2/vendor/push-edx/flarum-ext-restricted-reply/src/Access/RestrictedReplyPolicy.php on line 71

Notice: Undefined variable: ability in /home/u857997072/public_html/forum/v2/vendor/push-edx/flarum-ext-restricted-reply/src/Access/RestrictedReplyPolicy.php on line 71

Notice: Undefined variable: ability in /home/u857997072/public_html/forum/v2/vendor/push-edx/flarum-ext-restricted-reply/src/Access/RestrictedReplyPolicy.php on line 71

Notice: Undefined variable: ability in /home/u857997072/public_html/forum/v2/vendor/push-edx/flarum-ext-restricted-reply/src/Access/RestrictedReplyPolicy.php on line 71

Notice: Undefined variable: ability in /home/u857997072/public_html/forum/v2/vendor/push-edx/flarum-ext-restricted-reply/src/Access/RestrictedReplyPolicy.php on line 71

Notice: Undefined variable: ability in /home/u857997072/public_html/forum/v2/vendor/push-edx/flarum-ext-restricted-reply/src/Access/RestrictedReplyPolicy.php on line 71

Fatal error: Uncaught RuntimeException: Output has been emitted previously; cannot emit response in /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-diactoros/src/Response/SapiEmitterTrait.php:31 Stack trace: #0 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-diactoros/src/Response/SapiEmitter.php(27): Zend\Diactoros\Response\SapiEmitter->assertNoPreviousOutput() #1 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-diactoros/src/Server.php(162): Zend\Diactoros\Response\SapiEmitter->emit(Object(Zend\Diactoros\Response)) #2 /home/u857997072/public_html/forum/v2/vendor/flarum/core/src/Http/AbstractServer.php(36): Zend\Diactoros\Server->listen(Object(Zend\Stratigility\NoopFinalHandler)) #3 /home/u857997072/public_html/forum/v2/index.php(15): Flarum\Http\AbstractServer->listen() #4 {main} thrown in /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-diactoros/src/Response/SapiEmitterTrait.php on line 31
```

**php flarum info**

```
Flarum core 0.1.0-beta.7
PHP 7.0.30
Loaded extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, calendar, ctype, curl, hash, filter, ftp, gettext, gmp, SPL, iconv, pcntl, readline, Reflection, session, standard, shmop, SimpleXML, mbstring, tokenizer, xml, bcmath, dom, fileinfo, gd, imagick, imap, intl, json, exif, mcrypt, mysqlnd, mysqli, PDO, pdo_mysql, pdo_sqlite, phalcon, Phar, posix, pspell, soap, sockets, tidy, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader
EXT flagrow-analytics 0.6.0
EXT flarum-approval v0.1.0-beta.7
EXT noriods-auto-more 0.2.0
EXT sides-autovid 0.1.0-beta.3
EXT flarum-bbcode v0.1.0-beta.5
EXT oe800-bbcode-alerts 0.1.6
EXT freshman-bbcode-with-textalign v1.0.4
EXT oe800-bbcode-cards 0.1.4
EXT antoinefr-bbcode-fa v0.1.1
EXT oe800-bbcode-pastebin 0.1.2
EXT oe800-bbcode-bars 0.1.5
EXT oe800-bbcode-special 0.1.5
EXT oe800-bbcode-tables 0.1.0
EXT beeta-dev-ext-quickquote 0.2.1
EXT beeta-dev-ext-userinfo 0.3.3
EXT zaptech-cookie-consent 0.1.0-beta3
EXT hyn-default-group 0.5.0
EXT sijad-details 0.1.2
EXT michaelbelgium-discussion-views v0.1.0-beta.7-3.1
EXT flarum-emoji v0.1.0-beta.6
EXT clarkwinkelmann-emojionearea 0.1.2
EXT flarum-english v0.1.0-beta.7
EXT issyrocks12-filter 1.2.2
EXT flagrow-ads 0.1.0-beta.4
EXT flagrow-bazaar 0.2.4
EXT flagrow-byobu 0.1.2
EXT flagrow-canned-messages 0.1.0
EXT flagrow-auto-confirm-fix 0.1.0
EXT flagrow-impersonate 0.1.0
EXT flagrow-linguist 0.1.2
EXT flagrow-terms 0.1.2
EXT flagrow-upload 0.6.0
EXT flagrow-user-directory 0.1.0
EXT flarum-flags v0.1.0-beta.7
EXT milescellar-french v1.1.0
EXT sijad-recaptcha 0.0.2
EXT antriver-http-hooks 0.0.3
EXT clarkwinkelmann-high-contrast 0.1.1
EXT matpompili-imgur-upload v1.0.0
EXT flagrow-latex 0.1.1
EXT flarum-likes v0.1.0-beta.6
EXT sijad-links 0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT ganuonglachanh-markdown-editor 0.9
EXT flarumchina-mediaembed-pro 0.3.6
EXT flarum-mentions v0.1.0-beta.7
EXT isaa-isaa-opengraph 0.1
EXT sijad-pages 0.1.0-beta.3
EXT q7zh-ratings v1.0.1
EXT michaelbelgium-profile-views v0.1.0-beta-7-1
EXT flarum-pusher v0.1.0-beta.6
EXT reflar-gamification 3.0.4
EXT reflar-koseki 0.1.3
EXT reflar-nightmode 0.1.4
EXT reflar-polls 1.2.3
EXT reflar-reactions 1.0.0-beta.4
EXT push-edx-chat 0.6.0
EXT zeokat-seoslugs v0.1.1
EXT ganuonglachanh-search 0.4
EXT davis-socialprofile 0.2.3
EXT sijad-spoiler-alert 0.1.0
EXT sijad-auth-steam 0.1.10
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT amaurycarrade-syndication v0.1.5
EXT flarum-tags v0.1.0-beta.8
EXT ahrasis-tenancy-group v0.0.1
EXT avatar4eg-users-list 0.1.1
EXT vingle-share-social 0.1.0
Base URL: https://manslandlife.tk/forum/v2
```

**Comment by weierophinney** [comment]
I have no idea what Flarum is, but the problem lies there, and not with Diactoros, based on the last line of the trace:

```text
Output has been emitted previously; cannot emit response 
```

I'm assuming you're using something like `Zend\Diactoros\Server` and/or `Zend\Diactoros\Response\SapiEmitter`. This latter _requires_ that the application ensure no headers have been sent previously. This includes ensuring that no `echo`, `print`, `printf`, `var_dump`, or other similar statements that emit content to the output buffer are called, as doing so implicitly causes PHP to send headers so that it can begin sending the buffer contents to the client.

This has happened in the application you are executing, and happened when an argument was omitted when instantiating a class, as indicated by the first line of the trace you provided:

```text
Warning: Missing argument 2 for Zurtr\OneSignal\OneSignalAPI::__construct(), called in /home/u857997072/public_html/forum/v2/vendor/zurtr/flarum-ext-onesignal/src/Listener/SendWebPushNotification.php on line 21 and defined in /home/u857997072/public_html/forum/v2/vendor/zurtr/flarum-ext-onesignal/src/OneSignalAPI.php on line 9
```

My guess is that the `SendWebPushNotification` listener is not properly instantiating a `OneSignalAPI` instance. This is not a problem in Diactoros.

**Comment by datitisev** [comment]
One of the extensions is for beta 7

**Comment by luceos** [comment]
@weierophinney thanks for jumping in, my apologies for drawing unwanted attention. Please ignore the report files on the diactoros repository.

@KazeroG next time, as suggested on the forums, ask for confirmation first before reporting a **possible** (for you) huge issue like. Also, as @datitisev and the answer on [this issue](https://github.com/Push-EDX/flarum-ext-restricted-reply/issues/2#issuecomment-388898644) points out is the issue caused by an outdated extension.
