### ISSUE TITLE
Permission denied when replying or mentioning

### ISSUE THREAD

**Issue by malago86** [flarum/core#1987]
## Bug Report

**Current Behavior**
The forum shows an error when replying to a post or mentioning (with @) in any post.

**Steps to Reproduce**
1. Go to ANY POST
2. Click on REPLY to any post or start replying and write @

**Expected Behavior**
The forum uses the "Mentions" extension which seems to be the cause of the problem, without it, there is no way to reply to specific posts or mention people with @ so the problem is gone, but I need this functionality.

**Environment**
- Flarum version: 0.1.0-beta.11.1
- Website URL: http://diablonext.com/foros
- Webserver: apache
- Hosting environment: vps
- PHP version: 7.2.24

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```
Flarum core 0.1.0-beta.11.1
PHP version: 7.2.24-0ubuntu0.18.04.2
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, sodium, session, standard, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, json, exif, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, Zend OPcache
+--------------------------+----------------+--------+
| Flarum Extensions        |                |        |
+--------------------------+----------------+--------+
| ID                       | Version        | Commit |
+--------------------------+----------------+--------+
| flarum-bbcode            | v0.1.0-beta.8  |        |
| flarum-emoji             | v0.1.0-beta.10 |        |
| flarum-lang-english      | v0.1.0-beta.11 |        |
| flarum-flags             | v0.1.0-beta.10 |        |
| flarum-lock              | v0.1.0-beta.9  |        |
| flarum-markdown          | v0.1.0-beta.10 |        |
| flarum-statistics        | v0.1.0-beta.9  |        |
| flarum-subscriptions     | v0.1.0-beta.9  |        |
| flarum-suspend           | v0.1.0-beta.10 |        |
| flarum-tags              | v0.1.0-beta.11 |        |
| flarum-sticky            | v0.1.0-beta.9  |        |
| flagrow-analytics        | 0.8.0          |        |
| v17development-seo       | 1.1            |        |
| fof-ban-ips              | 0.1.5          |        |
| darkfoxdeveloper-spanish | v1.0.5         |        |
| fof-formatting           | 0.1.4          |        |
| fof-links                | 0.2.1          |        |
| fof-transliterator       | 0.2.0          |        |
| fof-linguist             | 0.4.1          |        |
| fof-masquerade           | 0.3.3          |        |
| flarum-likes             | v0.1.0-beta.9  |        |
| extiverse-bazaar         | 0.4.1          |        |
| oe800-bbcode-alerts      | 0.2.0          |        |
| flagrow-sitemap          | 0.2.0          |        |
| flarum-mentions          | v0.1.0-beta.10 |        |
+--------------------------+----------------+--------+
Base URL: https://www.diablonext.com/foros
Installation path: /home/diablonext/public_html/foros
Debug mode: ON

**Possible Solution**
Something seems to be wrong with permissions to reply or mention but the administration does not have anything to change those permissions.

**Additional Context**
This is the stack trace for the error:

GET https://www.diablonext.com/foros/api/users?filter%5Bq%5D=gayardos%23699%20&page%5Blimit%5D=5

{
  "errors": [
    {
      "status": "403",
      "code": "permission_denied",
      "detail": "Flarum\\User\\Exception\\PermissionDeniedException in /home/diablonext/public_html/foros/vendor/flarum/core/src/User/AssertPermissionTrait.php:31\nStack trace:\n#0 /home/diablonext/public_html/foros/vendor/flarum/core/src/User/AssertPermissionTrait.php(61): Flarum\\Api\\Controller\\ListUsersController->assertPermission(false)\n#1 /home/diablonext/public_html/foros/vendor/flarum/core/src/Api/Controller/ListUsersController.php(73): Flarum\\Api\\Controller\\ListUsersController->assertCan(Object(Flarum\\User\\User), 'viewUserList')\n#2 /home/diablonext/public_html/foros/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(96): Flarum\\Api\\Controller\\ListUsersController->data(Object(Zend\\Diactoros\\ServerRequest), Object(Tobscure\\JsonApi\\Document))\n#3 /home/diablonext/public_html/foros/vendor/flarum/core/src/Http/RouteHandlerFactory.php(38): Flarum\\Api\\Controller\\AbstractSerializeController->handle(Object(Zend\\Diactoros\\ServerRequest))\n#4 /home/diablonext/public_html/foros/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(65): Flarum\\Http\\RouteHandlerFactory->Flarum\\Http\\{closure}(Object(Zend\\Diactoros\\ServerRequest), Array)\n#5 /home/diablonext/public_html/foros/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\DispatchRoute->process(Object(Zend\\Diactoros\\ServerRequest), Object(Closure))\n#6 /home/diablonext/public_html/foros/vendor/flarum/core/src/Http/Middleware/SetLocale.php(50): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#7 /home/diablonext/public_html/foros/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\SetLocale->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#8 /home/diablonext/public_html/foros/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(23): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#9 /home/diablonext/public_html/foros/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\CheckCsrfToken->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#10 /home/diablonext/public_html/foros/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(55): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#11 /home/diablonext/public_html/foros/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\AuthenticateWithHeader->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#12 /home/diablonext/public_html/foros/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(32): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#13 /home/diablonext/public_html/foros/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\AuthenticateWithSession->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#14 /home/diablonext/public_html/foros/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(51): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#15 /home/diablonext/public_html/foros/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\RememberFromCookie->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#16 /home/diablonext/public_html/foros/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#17 /home/diablonext/public_html/foros/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\StartSession->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#18 /home/diablonext/public_html/foros/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#19 /home/diablonext/public_html/foros/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Api\\Middleware\\FakeHttpMethods->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#20 /home/diablonext/public_html/foros/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#21 /home/diablonext/public_html/foros/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\ParseJsonBody->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#22 /home/diablonext/public_html/foros/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#23 /home/diablonext/public_html/foros/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\\Http\\Middleware\\HandleErrors->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#24 /home/diablonext/public_html/foros/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(83): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#25 /home/diablonext/public_html/foros/vendor/middlewares/request-handler/src/RequestHandler.php(84): Zend\\Stratigility\\MiddlewarePipe->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#26 /home/diablonext/public_html/foros/vendor/zendframework/zend-stratigility/src/Next.php(60): Middlewares\\RequestHandler->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#27 /home/diablonext/public_html/foros/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#28 /home/diablonext/public_html/foros/vendor/zendframework/zend-stratigility/src/Next.php(60): Middlewares\\BasePathRouter->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#29 /home/diablonext/public_html/foros/vendor/zendframework/zend-stratigility/src/Middleware/OriginalMessages.php(41): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#30 /home/diablonext/public_html/foros/vendor/zendframework/zend-stratigility/src/Next.php(60): Zend\\Stratigility\\Middleware\\OriginalMessages->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#31 /home/diablonext/public_html/foros/vendor/middlewares/base-path/src/BasePath.php(53): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#32 /home/diablonext/public_html/foros/vendor/zendframework/zend-stratigility/src/Next.php(60): Middlewares\\BasePath->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\Next))\n#33 /home/diablonext/public_html/foros/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(83): Zend\\Stratigility\\Next->handle(Object(Zend\\Diactoros\\ServerRequest))\n#34 /home/diablonext/public_html/foros/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(72): Zend\\Stratigility\\MiddlewarePipe->process(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Stratigility\\EmptyPipelineHandler))\n#35 /home/diablonext/public_html/foros/vendor/zendframework/zend-httphandlerrunner/src/RequestHandlerRunner.php(95): Zend\\Stratigility\\MiddlewarePipe->handle(Object(Zend\\Diactoros\\ServerRequest))\n#36 /home/diablonext/public_html/foros/vendor/flarum/core/src/Http/Server.php(44): Zend\\HttpHandlerRunner\\RequestHandlerRunner->run()\n#37 /home/diablonext/public_html/foros/index.php(22): Flarum\\Http\\Server->listen()\n#38 {main}"
    }
  ]
}

**Comment by malago86** [comment]
I just found out that it was because permissions to see user list was only set to admins and not all users... A bit confusing!
