### ISSUE TITLE
PHP mail not working

### ISSUE THREAD

**Issue by rafaucau** [flarum/core#2680]
## Bug Report
When I set the mail driver to `mail`, sending emails stops working.

**Current Behavior**
When I try to send a test email, I get the error: 
```
<br />
<b>Warning</b>: proc_open() has been disabled for security reasons in <b>/home/klient.dhosting.pl/androiddev/forum-beta.android.com.pl/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php</b> on line <b>291</b><br />
<br />
<b>Warning</b>: stream_set_blocking() expects parameter 1 to be resource, null given in <b>/home/klient.dhosting.pl/androiddev/forum-beta.android.com.pl/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php</b> on line <b>292</b><br />
<br />
<b>Warning</b>: stream_get_contents() expects parameter 1 to be resource, null given in <b>/home/klient.dhosting.pl/androiddev/forum-beta.android.com.pl/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php</b> on line <b>293</b><br />
<br />
<b>Fatal error</b>: Uncaught Laminas\HttpHandlerRunner\Exception\EmitterException: Unable to emit response; headers already sent in /home/klient.dhosting.pl/androiddev/forum-beta.android.com.pl/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php:19
Stack trace:
#0 /home/klient.dhosting.pl/androiddev/forum-beta.android.com.pl/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitterTrait.php(36): Laminas\HttpHandlerRunner\Exception\EmitterException::forHeadersSent()
#1 /home/klient.dhosting.pl/androiddev/forum-beta.android.com.pl/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitter.php(27): Laminas\HttpHandlerRunner\Emitter\SapiEmitter-&gt;assertNoPreviousOutput()
#2 /home/klient.dhosting.pl/androiddev/forum-beta.android.com.pl/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(98): Laminas\HttpHandlerRunner\Emitter\SapiEmitter-&gt;emit(Object(Flarum\Api\JsonApiResponse))
#3 /home/klient.dhosting.pl/androiddev/forum-beta.android.com.pl/vendor/flarum/core/src/Http/Server.php( in <b>/home/klient.dhosting.pl/androiddev/forum-beta.android.com.pl/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php</b> on line <b>19</b><br />
```

I tested it locally too and got another error:
```
<br />
<b>Fatal error</b>:  Uncaught InvalidArgumentException: Unable to encode data to JSON in Laminas\Diactoros\Response\JsonResponse: Malformed UTF-8 characters, possibly incorrectly encoded in D:\Serwer\wamp\www\flarum\vendor\laminas\laminas-diactoros\src\Response\JsonResponse.php:165
Stack trace:
#0 D:\Serwer\wamp\www\flarum\vendor\laminas\laminas-diactoros\src\Response\JsonResponse.php(83): Laminas\Diactoros\Response\JsonResponse-&gt;jsonEncode(Array, 15)
#1 D:\Serwer\wamp\www\flarum\vendor\flarum\core\src\Api\JsonApiResponse.php(27): Laminas\Diactoros\Response\JsonResponse-&gt;__construct(Array, 500, Array, 15)
#2 D:\Serwer\wamp\www\flarum\vendor\flarum\core\src\Foundation\ErrorHandling\JsonApiFormatter.php(41): Flarum\Api\JsonApiResponse-&gt;__construct(Object(Tobscure\JsonApi\Document), 500)
#3 D:\Serwer\wamp\www\flarum\vendor\flarum\core\src\Http\Middleware\HandleErrors.php(67): Flarum\Foundation\ErrorHandling\JsonApiFormatter-&gt;format(Object(Flarum\Foundation\ErrorHandling\HandledError), Object(Laminas\Diactoros\ServerRequest))
#4 D:\S in <b>D:\Serwer\wamp\www\flarum\vendor\laminas\laminas-diactoros\src\Response\JsonResponse.php</b> on line <b>165</b><br />
```

**Steps to Reproduce**
1. Set email driver to `mail`
2. Send test mail

**Expected Behavior**
Sending emails using PHP should work,

**Screenshots**

On hosting:
![image](https://user-images.githubusercontent.com/25438601/110531136-7f9c9380-811b-11eb-95b1-d2652c411e1f.png)

On local:
![image](https://user-images.githubusercontent.com/25438601/110532138-c2ab3680-811c-11eb-8a10-4dbcb9a711f0.png)

**Environment**
- Flarum version: 0.1.0-beta.15
- Webserver: Apache, Litespeed
- Hosting environment: shared
- PHP version: 7.4

**Comment by askvortsov1** [comment]
Can you confirm that `sendmail` works over the CLI (something like https://clients.javapipe.com/knowledgebase/132/How-to-Test-Sendmail-From-Command-Line-on-Linux.html)? It seems to me like this is an issue with your hosting provider and their security config rather than with Flarum.

**Comment by rafaucau** [comment]
Mail works on other sites on this hosting. Only Flarum has this problem.
BTW. `mail` didn't work on older versions of Flarum (https://discuss.flarum.org/d/12142-mail-not-working-and-no-logs-visible/10). Now there is such a difference that it displays an error message.

**Comment by Ralkage** [comment]
As @askvortsov1 stated, this is an issue with your hosting provider. They may have very well likely added `proc_open` to your php.ini file's disable_functions setting.

If you have access to it, you can remove it from that setting. If not, you'll have to ask your host to do it.

**Comment by askvortsov1** [comment]
Closing as this is a platform issue.
