### ISSUE TITLE
[Akismet] Error on user posting

### ISSUE THREAD

**Issue by tankerkiller125** [flarum/core#2768]
## Bug Report

**Current Behavior**
500 Errors

**Steps to Reproduce**
1. Create a post as a regular member

**Expected Behavior**
Should not error

**Error Log**
```
[2021-04-06 20:23:25] flarum.ERROR: TijsVerkoyen\Akismet\Exception in /home/forge/discuss.flarum.org/vendor/tijsverkoyen/akismet/Akismet.php:159
Stack trace:
#0 /home/forge/discuss.flarum.org/vendor/tijsverkoyen/akismet/Akismet.php(363): TijsVerkoyen\Akismet\Akismet->doCall()
#1 /home/forge/discuss.flarum.org/vendor/flarum/akismet/src/Listener/ValidatePost.php(41): TijsVerkoyen\Akismet\Akismet->isSpam()
#2 /home/forge/discuss.flarum.org/vendor/illuminate/events/Dispatcher.php(412): Flarum\Akismet\Listener\ValidatePost->handle()
#3 /home/forge/discuss.flarum.org/vendor/illuminate/events/Dispatcher.php(237): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}()
#4 /home/forge/discuss.flarum.org/vendor/flarum/core/src/Post/Command/PostReplyHandler.php(96): Illuminate\Events\Dispatcher->dispatch()
#5 /home/forge/discuss.flarum.org/vendor/illuminate/bus/Dispatcher.php(122): Flarum\Post\Command\PostReplyHandler->handle()
#6 /home/forge/discuss.flarum.org/vendor/illuminate/pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#7 /home/forge/discuss.flarum.org/vendor/illuminate/pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#8 /home/forge/discuss.flarum.org/vendor/illuminate/bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#9 /home/forge/discuss.flarum.org/vendor/illuminate/bus/Dispatcher.php(78): Illuminate\Bus\Dispatcher->dispatchNow()
#10 /home/forge/discuss.flarum.org/vendor/flarum/core/src/Api/Controller/CreatePostController.php(61): Illuminate\Bus\Dispatcher->dispatch()
#11 /home/forge/discuss.flarum.org/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(102): Flarum\Api\Controller\CreatePostController->data()
#12 /home/forge/discuss.flarum.org/vendor/flarum/core/src/Api/Controller/AbstractCreateController.php(22): Flarum\Api\Controller\AbstractSerializeController->handle()
#13 /home/forge/discuss.flarum.org/vendor/flarum/core/src/Http/RouteHandlerFactory.php(38): Flarum\Api\Controller\AbstractCreateController->handle()
#14 /home/forge/discuss.flarum.org/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#15 /home/forge/discuss.flarum.org/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ExecuteRoute->process()
#16 /home/forge/discuss.flarum.org/vendor/kilowhat/flarum-ext-audit-pro/src/Middlewares/ExtendSetPermissionController.php(19): Laminas\Stratigility\Next->handle()
#17 /home/forge/discuss.flarum.org/vendor/laminas/laminas-stratigility/src/Next.php(61): Kilowhat\Audit\Middlewares\ExtendSetPermissionController->process()
#18 /home/forge/discuss.flarum.org/vendor/kilowhat/flarum-ext-audit-pro/src/Middlewares/SetLoggerActor.php(27): Laminas\Stratigility\Next->handle()
#19 /home/forge/discuss.flarum.org/vendor/laminas/laminas-stratigility/src/Next.php(61): Kilowhat\Audit\Middlewares\SetLoggerActor->process()
#20 /home/forge/discuss.flarum.org/vendor/flarum/core/src/Api/Middleware/ThrottleApi.php(33): Laminas\Stratigility\Next->handle()
#21 /home/forge/discuss.flarum.org/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Api\Middleware\ThrottleApi->process()
#22 /home/forge/discuss.flarum.org/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(44): Laminas\Stratigility\Next->handle()
#23 /home/forge/discuss.flarum.org/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\CheckCsrfToken->process()
#24 /home/forge/discuss.flarum.org/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(67): Laminas\Stratigility\Next->handle()
#25 /home/forge/discuss.flarum.org/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ResolveRoute->process()
#26 /home/forge/discuss.flarum.org/vendor/flarum/core/src/Http/Middleware/SetLocale.php(50): Laminas\Stratigility\Next->handle()
#27 /home/forge/discuss.flarum.org/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\SetLocale->process()
#28 /home/forge/discuss.flarum.org/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(55): Laminas\Stratigility\Next->handle()
#29 /home/forge/discuss.flarum.org/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\AuthenticateWithHeader->process()
#30 /home/forge/discuss.flarum.org/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(32): Laminas\Stratigility\Next->handle()
#31 /home/forge/discuss.flarum.org/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\AuthenticateWithSession->process()
#32 /home/forge/discuss.flarum.org/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Laminas\Stratigility\Next->handle()
#33 /home/forge/discuss.flarum.org/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\RememberFromCookie->process()
#34 /home/forge/discuss.flarum.org/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#35 /home/forge/discuss.flarum.org/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\StartSession->process()
#36 /home/forge/discuss.flarum.org/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Laminas\Stratigility\Next->handle()
#37 /home/forge/discuss.flarum.org/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Api\Middleware\FakeHttpMethods->process()
#38 /home/forge/discuss.flarum.org/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#39 /home/forge/discuss.flarum.org/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ParseJsonBody->process()
#40 /home/forge/discuss.flarum.org/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#41 /home/forge/discuss.flarum.org/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\HandleErrors->process()
#42 /home/forge/discuss.flarum.org/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#43 /home/forge/discuss.flarum.org/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#44 /home/forge/discuss.flarum.org/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\RequestHandler->process()
#45 /home/forge/discuss.flarum.org/vendor/middlewares/base-path-router/src/BasePathRouter.php(101): Laminas\Stratigility\Next->handle()
#46 /home/forge/discuss.flarum.org/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePathRouter->process()
#47 /home/forge/discuss.flarum.org/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(42): Laminas\Stratigility\Next->handle()
#48 /home/forge/discuss.flarum.org/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\Middleware\OriginalMessages->process()
#49 /home/forge/discuss.flarum.org/vendor/middlewares/base-path/src/BasePath.php(53): Laminas\Stratigility\Next->handle()
#50 /home/forge/discuss.flarum.org/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePath->process()
#51 /home/forge/discuss.flarum.org/vendor/flarum/core/src/Http/Middleware/ProcessIp.php(24): Laminas\Stratigility\Next->handle()
#52 /home/forge/discuss.flarum.org/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ProcessIp->process()
#53 /home/forge/discuss.flarum.org/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#54 /home/forge/discuss.flarum.org/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(73): Laminas\Stratigility\MiddlewarePipe->process()
#55 /home/forge/discuss.flarum.org/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle()
#56 /home/forge/discuss.flarum.org/vendor/flarum/core/src/Http/Server.php(44): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#57 /home/forge/discuss.flarum.org/public/index.php(22): Flarum\Http\Server->listen()
#58 {main}  
```

**Environment**
- Flarum version: v0.1.0-beta.16
- Website URL: https://discuss.flarum.org
- Webserver: nginx
- Hosting environment: Discuss (DigitalOcean
- PHP version: 8.0
- Browser: Any

**Comment by tankerkiller125** [comment]
Closing as this is the same issue as #2691
