### ISSUE TITLE
Avatar upload broken due to dependency error in intervention/image

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/core#2966]
## Bug Report

**Current Behavior**
New Flarum installations since last week encounter a 500 error when uploading an avatar.

**Steps to Reproduce**
1. Install Flarum.
2. `intervention/image` package version will be 2.6.0
3. Upload any image on any user profile
4. "Oops" error message appears

Error in log:

```
[2021-07-14 21:05:30] flarum.ERROR: Error: Call to undefined function GuzzleHttp\Psr7\stream_for() in /home/clark/Projects/flarum-1.0/vendor/intervention/image/src/Intervention/Image/Commands/StreamCommand.php:19
Stack trace:
#0 /home/clark/Projects/flarum-1.0/vendor/intervention/image/src/Intervention/Image/AbstractDriver.php(94): Intervention\Image\Commands\StreamCommand->execute()
#1 /home/clark/Projects/flarum-1.0/vendor/intervention/image/src/Intervention/Image/Image.php(108): Intervention\Image\AbstractDriver->executeCommand()
#2 /home/clark/Projects/flarum-1.0/vendor/intervention/image/src/Intervention/Image/Commands/ExifCommand.php(35): Intervention\Image\Image->__call()
#3 /home/clark/Projects/flarum-1.0/vendor/intervention/image/src/Intervention/Image/AbstractDriver.php(94): Intervention\Image\Commands\ExifCommand->execute()
#4 /home/clark/Projects/flarum-1.0/vendor/intervention/image/src/Intervention/Image/Image.php(108): Intervention\Image\AbstractDriver->executeCommand()
#5 /home/clark/Projects/flarum-1.0/vendor/intervention/image/src/Intervention/Image/Commands/OrientateCommand.php(15): Intervention\Image\Image->__call()
#6 /home/clark/Projects/flarum-1.0/vendor/intervention/image/src/Intervention/Image/AbstractDriver.php(94): Intervention\Image\Commands\OrientateCommand->execute()
#7 /home/clark/Projects/flarum-1.0/vendor/intervention/image/src/Intervention/Image/Image.php(108): Intervention\Image\AbstractDriver->executeCommand()
#8 /home/clark/Projects/flarum-1.0/vendor/flarum/core/src/User/AvatarUploader.php(36): Intervention\Image\Image->__call()
#9 /home/clark/Projects/flarum-1.0/vendor/flarum/core/src/User/Command/UploadAvatarHandler.php(77): Flarum\User\AvatarUploader->upload()
#10 /home/clark/Projects/flarum-1.0/vendor/illuminate/bus/Dispatcher.php(122): Flarum\User\Command\UploadAvatarHandler->handle()
#11 /home/clark/Projects/flarum-1.0/vendor/illuminate/pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#12 /home/clark/Projects/flarum-1.0/vendor/illuminate/pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#13 /home/clark/Projects/flarum-1.0/vendor/illuminate/bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#14 /home/clark/Projects/flarum-1.0/vendor/illuminate/bus/Dispatcher.php(78): Illuminate\Bus\Dispatcher->dispatchNow()
#15 /home/clark/Projects/flarum-1.0/vendor/flarum/core/src/Api/Controller/UploadAvatarController.php(50): Illuminate\Bus\Dispatcher->dispatch()
#16 /home/clark/Projects/flarum-1.0/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(110): Flarum\Api\Controller\UploadAvatarController->data()
#17 /home/clark/Projects/flarum-1.0/vendor/flarum/core/src/Http/RouteHandlerFactory.php(41): Flarum\Api\Controller\AbstractSerializeController->handle()
#18 /home/clark/Projects/flarum-1.0/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#19 /home/clark/Projects/flarum-1.0/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ExecuteRoute->process()
#20 /home/clark/Projects/flarum-1.0/vendor/flarum/core/src/Api/Middleware/ThrottleApi.php(33): Laminas\Stratigility\Next->handle()
#21 /home/clark/Projects/flarum-1.0/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Api\Middleware\ThrottleApi->process()
#22 /home/clark/Projects/flarum-1.0/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(44): Laminas\Stratigility\Next->handle()
#23 /home/clark/Projects/flarum-1.0/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\CheckCsrfToken->process()
#24 /home/clark/Projects/flarum-1.0/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(67): Laminas\Stratigility\Next->handle()
#25 /home/clark/Projects/flarum-1.0/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ResolveRoute->process()
#26 /home/clark/Projects/flarum-1.0/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle()
#27 /home/clark/Projects/flarum-1.0/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\SetLocale->process()
#28 /home/clark/Projects/flarum-1.0/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(56): Laminas\Stratigility\Next->handle()
#29 /home/clark/Projects/flarum-1.0/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\AuthenticateWithHeader->process()
#30 /home/clark/Projects/flarum-1.0/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(31): Laminas\Stratigility\Next->handle()
#31 /home/clark/Projects/flarum-1.0/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\AuthenticateWithSession->process()
#32 /home/clark/Projects/flarum-1.0/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Laminas\Stratigility\Next->handle()
#33 /home/clark/Projects/flarum-1.0/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\RememberFromCookie->process()
#34 /home/clark/Projects/flarum-1.0/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#35 /home/clark/Projects/flarum-1.0/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\StartSession->process()
#36 /home/clark/Projects/flarum-1.0/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Laminas\Stratigility\Next->handle()
#37 /home/clark/Projects/flarum-1.0/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Api\Middleware\FakeHttpMethods->process()
#38 /home/clark/Projects/flarum-1.0/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#39 /home/clark/Projects/flarum-1.0/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ParseJsonBody->process()
#40 /home/clark/Projects/flarum-1.0/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#41 /home/clark/Projects/flarum-1.0/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\HandleErrors->process()
#42 /home/clark/Projects/flarum-1.0/vendor/flarum/core/src/Http/Middleware/InjectActorReference.php(25): Laminas\Stratigility\Next->handle()
#43 /home/clark/Projects/flarum-1.0/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\InjectActorReference->process()
#44 /home/clark/Projects/flarum-1.0/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#45 /home/clark/Projects/flarum-1.0/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#46 /home/clark/Projects/flarum-1.0/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\RequestHandler->process()
#47 /home/clark/Projects/flarum-1.0/vendor/middlewares/base-path-router/src/BasePathRouter.php(101): Laminas\Stratigility\Next->handle()
#48 /home/clark/Projects/flarum-1.0/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\BasePathRouter->process()
#49 /home/clark/Projects/flarum-1.0/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(36): Laminas\Stratigility\Next->handle()
#50 /home/clark/Projects/flarum-1.0/vendor/laminas/laminas-stratigility/src/Next.php(51): Laminas\Stratigility\Middleware\OriginalMessages->process()
#51 /home/clark/Projects/flarum-1.0/vendor/middlewares/base-path/src/BasePath.php(73): Laminas\Stratigility\Next->handle()
#52 /home/clark/Projects/flarum-1.0/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\BasePath->process()
#53 /home/clark/Projects/flarum-1.0/vendor/flarum/core/src/Http/Middleware/ProcessIp.php(24): Laminas\Stratigility\Next->handle()
#54 /home/clark/Projects/flarum-1.0/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ProcessIp->process()
#55 /home/clark/Projects/flarum-1.0/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#56 /home/clark/Projects/flarum-1.0/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(65): Laminas\Stratigility\MiddlewarePipe->process()
#57 /home/clark/Projects/flarum-1.0/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle()
#58 /home/clark/Projects/flarum-1.0/vendor/flarum/core/src/Http/Server.php(44): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#59 /home/clark/Projects/flarum-1.0/public/index.php(26): Flarum\Http\Server->listen()
#60 {main}  
```

**Environment**
- Flarum version: 1.0.4
- Hosting environment: local

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

**Possible Solution**
This is an issue that Intervention should fix in their package. It's reported on their bug tracker here https://github.com/Intervention/image/issues/1095

As a workaround we can explicitely require the old version of PSR7 package with `composer require guzzlehttp/psr7:"^1.1"`

If Intervention fixes this quickly it's not really worth publishing a patch release on Flarum to fix that dependency version.

**Additional Context**
Issue reported here https://discuss.flarum.org/d/28160-profile-imagecover-upload-error/3

Probably affects everyone who installed or updated with all dependencies in the last week since intervention/image 2.6.0 was tagged.

**Comment by StarsRivers** [comment]
Same problem, thanks for providing a temporary solution!
