### ISSUE TITLE
Changing forum color renders site unusable

### ISSUE THREAD

**Issue by connor557** [flarum/core#3188]
## Bug Report

**Current Behavior**
Changing the forum color renders the site unusable

**Steps to Reproduce**
1. Go to 'Administration'
2. Click on 'Appearance'
3. Scroll down to 'Colors'
4. Change the color to anything
5. See error

**Expected Behavior**
The forum color will change

**Screenshots**

**Environment**
- Flarum version: x.y.z
- Website URL: http://sunrisenet.org
- Webserver: apache
- Hosting environment: rack server
- PHP version: 7.4
- Browser: chrome 92
 
**Error in main log file**

```
[2021-12-05 14:44:24] flarum.ERROR: Less_Exception_Compiler: error evaluating function `hue` The first argument to hue must be a color (did you forgot commas?) index: 424 in variables.less in /var/www/html/sunrisenet.org/vendor/wikimedia/less.php/lib/Less/Tree/Mixin/Call.php:125
Stack trace:
#0 /var/www/html/sunrisenet.org/vendor/wikimedia/less.php/lib/Less/Tree/Ruleset.php(143): Less_Tree_Mixin_Call->compile()
#1 /var/www/html/sunrisenet.org/vendor/wikimedia/less.php/lib/Less/Tree/Ruleset.php(86): Less_Tree_Ruleset->EvalMixinCalls()
#2 /var/www/html/sunrisenet.org/vendor/wikimedia/less.php/lib/Less/Parser.php(190): Less_Tree_Ruleset->compile()
#3 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Frontend/Compiler/LessCompiler.php(102): Less_Parser->getCss()
#4 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Frontend/Compiler/RevisionCompiler.php(134): Flarum\Frontend\Compiler\LessCompiler->compile()
#5 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Frontend/Compiler/RevisionCompiler.php(72): Flarum\Frontend\Compiler\RevisionCompiler->save()
#6 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Frontend/Compiler/RevisionCompiler.php(107): Flarum\Frontend\Compiler\RevisionCompiler->commit()
#7 /var/www/html/sunrisenet.org/vendor/fof/nightmode/src/Content/Assets.php(48): Flarum\Frontend\Compiler\RevisionCompiler->getUrl()
#8 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Frontend/Frontend.php(62): FoF\NightMode\Content\Assets->__invoke()
#9 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Frontend/Frontend.php(54): Flarum\Frontend\Frontend->populate()
#10 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Frontend/Controller.php(32): Flarum\Frontend\Frontend->document()
#11 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Http/RouteHandlerFactory.php(41): Flarum\Frontend\Controller->handle()
#12 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#13 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ExecuteRoute->process()
#14 /var/www/html/sunrisenet.org/vendor/fof/clockwork/src/Middleware/BeforeRouteExecutionMiddleware.php(47): Laminas\Stratigility\Next->handle()
#15 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): FoF\Clockwork\Middleware\BeforeRouteExecutionMiddleware->process()
#16 /var/www/html/sunrisenet.org/vendor/fof/ban-ips/src/Middleware/RegisterMiddleware.php(94): Laminas\Stratigility\Next->handle()
#17 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): FoF\BanIPs\Middleware\RegisterMiddleware->process()
#18 /var/www/html/sunrisenet.org/vendor/fof/clockwork/src/Middleware/ClockworkMiddleware.php(48): Laminas\Stratigility\Next->handle()
#19 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): FoF\Clockwork\Middleware\ClockworkMiddleware->process()
#20 /var/www/html/sunrisenet.org/vendor/fof/discussion-language/src/Middleware/AddLanguageFilter.php(42): Laminas\Stratigility\Next->handle()
#21 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): FoF\DiscussionLanguage\Middleware\AddLanguageFilter->process()
#22 /var/www/html/sunrisenet.org/vendor/fof/masquerade/src/Middleware/DemandProfileCompletion.php(57): Laminas\Stratigility\Next->handle()
#23 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): FoF\Masquerade\Middleware\DemandProfileCompletion->process()
#24 /var/www/html/sunrisenet.org/vendor/fof/pwned-passwords/src/Middleware/CheckPasswordReset.php(64): Laminas\Stratigility\Next->handle()
#25 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): FoF\PwnedPasswords\Middleware\CheckPasswordReset->process()
#26 /var/www/html/sunrisenet.org/vendor/fof/pwned-passwords/src/Middleware/CheckLoginPassword.php(55): Laminas\Stratigility\Next->handle()
#27 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): FoF\PwnedPasswords\Middleware\CheckLoginPassword->process()
#28 /var/www/html/sunrisenet.org/vendor/fof/pwned-passwords/src/Middleware/PreventPwnedPassword.php(71): Laminas\Stratigility\Next->handle()
#29 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): FoF\PwnedPasswords\Middleware\PreventPwnedPassword->process()
#30 /var/www/html/sunrisenet.org/vendor/fof/secure-https/src/Middlewares/ContentSecurityPolicyMiddleware.php(32): Laminas\Stratigility\Next->handle()
#31 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): FoF\SecureHttps\Middlewares\ContentSecurityPolicyMiddleware->process()
#32 /var/www/html/sunrisenet.org/vendor/fof/stopforumspam/src/Middleware/RegisterMiddleware.php(77): Laminas\Stratigility\Next->handle()
#33 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): FoF\StopForumSpam\Middleware\RegisterMiddleware->process()
#34 /var/www/html/sunrisenet.org/vendor/fof/oauth/src/Middleware/ErrorHandler.php(50): Laminas\Stratigility\Next->handle()
#35 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): FoF\OAuth\Middleware\ErrorHandler->process()
#36 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Http/Middleware/ContentTypeOptionsHeader.php(21): Laminas\Stratigility\Next->handle()
#37 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ContentTypeOptionsHeader->process()
#38 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Http/Middleware/ReferrerPolicyHeader.php(30): Laminas\Stratigility\Next->handle()
#39 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ReferrerPolicyHeader->process()
#40 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Http/Middleware/FlarumPromotionHeader.php(30): Laminas\Stratigility\Next->handle()
#41 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\FlarumPromotionHeader->process()
#42 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Http/Middleware/ShareErrorsFromSession.php(57): Laminas\Stratigility\Next->handle()
#43 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ShareErrorsFromSession->process()
#44 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(36): Laminas\Stratigility\Next->handle()
#45 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\CheckCsrfToken->process()
#46 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(67): Laminas\Stratigility\Next->handle()
#47 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ResolveRoute->process()
#48 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle()
#49 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\SetLocale->process()
#50 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(31): Laminas\Stratigility\Next->handle()
#51 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\AuthenticateWithSession->process()
#52 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Laminas\Stratigility\Next->handle()
#53 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\RememberFromCookie->process()
#54 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#55 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\StartSession->process()
#56 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Http/Middleware/CollectGarbage.php(46): Laminas\Stratigility\Next->handle()
#57 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\CollectGarbage->process()
#58 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#59 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ParseJsonBody->process()
#60 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#61 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\HandleErrors->process()
#62 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Http/Middleware/InjectActorReference.php(25): Laminas\Stratigility\Next->handle()
#63 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\InjectActorReference->process()
#64 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#65 /var/www/html/sunrisenet.org/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#66 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\RequestHandler->process()
#67 /var/www/html/sunrisenet.org/vendor/middlewares/base-path-router/src/BasePathRouter.php(101): Laminas\Stratigility\Next->handle()
#68 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\BasePathRouter->process()
#69 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(36): Laminas\Stratigility\Next->handle()
#70 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): Laminas\Stratigility\Middleware\OriginalMessages->process()
#71 /var/www/html/sunrisenet.org/vendor/middlewares/base-path/src/BasePath.php(73): Laminas\Stratigility\Next->handle()
#72 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\BasePath->process()
#73 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Http/Middleware/ProcessIp.php(24): Laminas\Stratigility\Next->handle()
#74 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ProcessIp->process()
#75 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#76 /var/www/html/sunrisenet.org/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(65): Laminas\Stratigility\MiddlewarePipe->process()
#77 /var/www/html/sunrisenet.org/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle()
#78 /var/www/html/sunrisenet.org/vendor/flarum/core/src/Http/Server.php(44): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#79 /var/www/html/sunrisenet.org/public/index.php(26): Flarum\Http\Server->listen()
#80 {main}
```

**Output of php flarum info**

```
Flarum core 1.2.0-dev
PHP version: 7.4.26
MySQL version: 8.0.27-0ubuntu0.20.04.1
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, json, ldap, exif, mcrypt, mysqli, pdo_mysql, apc, posix, readline, shmop, SimpleXML, soap, sockets, ssh2, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, yaml, zip, Phar, Zend OPcache
+------------------------------------+------------+--------+
| Flarum Extensions                  |            |        |
+------------------------------------+------------+--------+
| ID                                 | Version    | Commit |
+------------------------------------+------------+--------+
| flarum-flags                       | dev-master |        |
| flarum-suspend                     | dev-master |        |
| flarum-markdown                    | dev-master |        |
| flarum-tags                        | dev-master |        |
| flarum-nicknames                   | dev-master |        |
| fof-spamblock                      | dev-master |        |
| fof-oauth                          | dev-master |        |
| fof-impersonate                    | dev-master |        |
| flarum-subscriptions               | dev-master |        |
| flarum-approval                    | dev-master |        |
| zerosonesfun-up                    | dev-main   |        |
| zerosonesfun-tracking              | dev-main   |        |
| zerosonesfun-tldr                  | dev-main   |        |
| zerosonesfun-meme                  | dev-main   |        |
| zerosonesfun-featured-card         | dev-main   |        |
| zerosonesfun-essential-audio       | dev-main   |        |
| zerosonesfun-chords                | dev-master |        |
| zerosonesfun-bbcode-button         | dev-main   |        |
| zerosonesfun-bbcode-advanced-image | dev-master |        |
| therealsujitk-gifs                 | dev-master |        |
| studosi-lang-croatian              | dev-master |        |
| rob006-lang-polish                 | dev-master |        |
| realodix-indonesian                | dev-master |        |
| ratthabiz-thai                     | dev-main   |        |
| ramesh-dada-medium-zoom            | dev-main   |        |
| project1537-lang-bosnian           | dev-main   |        |
| pipecraft-id-slug                  | dev-main   |        |
| opendir-font-awesome-6             | dev-main   |        |
| neerugupta-lang-arabic             | dev-master |        |
| nearata-lang-italian               | dev-main   |        |
| nearata-copy-code-to-clipboard     | dev-main   |        |
| miniflar-bbcode-progress-bars      | dev-main   |        |
| matteocontrini-imgur-upload        | dev-master |        |
| madnest-lang-czech                 | dev-master |        |
| kyrne-websocket                    | dev-master |        |
| justoverclock-thread-read-time     | dev-main   |        |
| justoverclock-hashtag              | dev-main   |        |
| justoverclock-discussion-info      | dev-main   |        |
| jhlee838-korean                    | dev-master |        |
| isaced-email-verification-switch   | dev-master |        |
| imshuzai-tooltip                   | dev-master |        |
| ianm-level-ranks                   | dev-master |        |
| futuresound-el                     | dev-master |        |
| fof-webhooks                       | dev-master |        |
| fof-username-request               | dev-master |        |
| fof-user-directory                 | dev-master |        |
| fof-user-bio                       | dev-master |        |
| fof-upload                         | dev-master |        |
| fof-subscribed                     | dev-master |        |
| fof-stopforumspam                  | dev-master |        |
| fof-split                          | dev-master |        |
| fof-socialprofile                  | dev-master |        |
| fof-sitemap                        | dev-master |        |
| fof-share-social                   | dev-master |        |
| fof-secure-https                   | dev-master |        |
| fof-recaptcha                      | dev-master |        |
| fof-realtimelogin                  | dev-master |        |
| fof-reactions                      | dev-master |        |
| fof-pwned-passwords                | dev-master |        |
| fof-profile-image-crop             | dev-master |        |
| fof-prevent-necrobumping           | dev-master |        |
| fof-pretty-mail                    | dev-master |        |
| fof-polls                          | dev-master |        |
| fof-pages                          | dev-master |        |
| fof-nightmode                      | dev-master |        |
| fof-moderator-notes                | dev-master |        |
| fof-masquerade                     | dev-master |        |
| fof-mason                          | dev-master |        |
| fof-links                          | dev-master |        |
| fof-linguist                       | dev-master |        |
| fof-ignore-users                   | dev-master |        |
| fof-html-errors                    | dev-master |        |
| fof-github-autolink                | dev-master |        |
| fof-geoip                          | dev-master |        |
| fof-gamification                   | dev-master |        |
| fof-frontpage                      | dev-master |        |
| fof-forum-statistics-widget        | dev-master |        |
| fof-formatting                     | dev-master |        |
| fof-follow-tags                    | dev-master |        |
| fof-filter                         | dev-master |        |
| fof-drafts                         | dev-master |        |
| fof-doorman                        | dev-master |        |
| fof-disposable-emails              | dev-master |        |
| fof-discussion-thumbnail           | dev-master |        |
| fof-discussion-language            | dev-master |        |
| fof-default-user-preferences       | dev-master |        |
| fof-default-group                  | dev-master |        |
| fof-custom-footer                  | dev-master |        |
| fof-cookie-consent                 | dev-master |        |
| fof-clockwork                      | dev-master |        |
| fof-bbcode-tabs                    | dev-master |        |
| fof-bbcode-details                 | dev-master |        |
| fof-ban-ips                        | dev-master |        |
| fof-analytics                      | dev-master |        |
| flarum-sticky                      | dev-master |        |
| flarum-statistics                  | dev-master |        |
| flarum-mentions                    | dev-master |        |
| flarum-lock                        | dev-master |        |
| flarum-likes                       | dev-master |        |
| flarum-lang-vietnamese             | dev-master |        |
| flarum-lang-uzbek                  | dev-master |        |
| flarum-lang-turkish                | dev-main   |        |
| flarum-lang-tamil                  | dev-main   |        |
| flarum-lang-swedish                | dev-main   |        |
| flarum-lang-spanish                | dev-main   |        |
| flarum-lang-slovak                 | dev-master |        |
| flarum-lang-sinhala                | dev-main   |        |
| flarum-lang-russian                | dev-main   |        |
| flarum-lang-romanian               | dev-main   |        |
| flarum-lang-persian                | dev-master |        |
| flarum-lang-japanese               | dev-master |        |
| flarum-lang-hungarian              | dev-master |        |
| flarum-lang-hindi                  | dev-master |        |
| flarum-lang-french                 | dev-master |        |
| flarum-lang-finnish                | dev-master |        |
| flarum-lang-english                | dev-master |        |
| flarum-lang-dutch                  | dev-main   |        |
| flarum-lang-azerbaijani            | dev-master |        |
| flarum-emoji                       | dev-master |        |
| flarum-bbcode                      | dev-master |        |
| flabrew-flabrew                    | dev-master |        |
| edevrob-lang-latvian               | dev-master |        |
| darkle-fancybox                    | dev-main   |        |
| clarkwinkelmann-username-blacklist | dev-main   |        |
| clarkwinkelmann-email-whitelist    | dev-main   |        |
| clarkwinkelmann-circle-groups      | dev-master |        |
| blomstra-mark-unread               | dev-master |        |
| askvortsov-rich-text               | dev-master |        |
| archlinux-de-discussion-feed       | 0.2.0      |        |
| 2nrwls-audio                       | dev-master |        |
+------------------------------------+------------+--------+
Base URL: https://sunrisenet.org
Installation path: /var/www/html/sunrisenet.org
Queue driver: sync
Mail driver: mail
Debug mode: off
```

**Comment by davwheat** [comment]
This is intentional if you attempt to enter an invalid colour, but I do think there should be a way to recover.

**Comment by datitisev** [comment]
This was probably why we had that color validation in place 🤔

**Comment by SychO9** [comment]
After the PR #3011 all less variable settings go through validation, I tested just now as well, and the forum should not be able to break when entering bad values. I see you're running `dev-master` (***which you really shouldn't be if on production***) what exact commit is that ?

![Screenshot from 2021-12-05 16-51-53](https://user-images.githubusercontent.com/20267363/144753678-f4dca3f2-5015-42b1-92d2-2e2f47a182c7.png)

**Comment by connor557** [comment]
Thanks all, the forum is not in production, I am currently testing the web server and will switch to a stable release before I run the system in production. I do not know exactly what commit I am running but can provide that information if someone tells me how. Please help me find a way to recover my site, thanks so much people.

**Comment by askvortsov1** [comment]
You'll need to go into the DB, and remove the relevant entries from the `settings` table.

**Comment by SychO9** [comment]
@connor557 the row in the settings table has a `key` column equal to `theme_primary_color`.

Also if you run `composer show flarum/core` it'll show you the exact commit in the `dist` value.

**Comment by connor557** [comment]
**Output of `composer show flarum/core`**

`
name     : flarum/core
descrip. : Delightfully simple forum software.
keywords : discussion, forum
versions : * dev-master, * 1.x-dev
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://flarum.org/
source   : [git] https://github.com/flarum/core.git dcc9868129d4144a602761a8150594b4881f7370
dist     : [zip] https://api.github.com/repos/flarum/core/zipball/dcc9868129d4144a602761a8150594b4881f7370 dcc9868129d4144a602761a8150594b4881f7370
path     : /var/www/html/sunrisenet.org/vendor/flarum/core
names    : flarum/core

support
chat : https://flarum.org/chat
docs : https://docs.flarum.org
forum : https://discuss.flarum.org
issues : https://github.com/flarum/core/issues
source : https://github.com/flarum/core

autoload
psr-4
Flarum\ => src/
files

requires
axy/sourcemap ^0.1.4
components/font-awesome ^5.14.0
dflydev/fig-cookies ^3.0.0
doctrine/dbal ^2.7
dragonmantank/cron-expression ^3.1.0
franzl/whoops-middleware ^2.0.0
illuminate/bus ^8.0
illuminate/cache ^8.0
illuminate/config ^8.0
illuminate/console ^8.0
illuminate/container ^8.0
illuminate/contracts ^8.0
illuminate/database ^8.0
illuminate/events ^8.0
illuminate/filesystem ^8.0
illuminate/hashing ^8.0
illuminate/mail ^8.0
illuminate/queue ^8.0
illuminate/session ^8.0
illuminate/support ^8.0
illuminate/validation ^8.0
illuminate/view ^8.0
intervention/image 2.5.* || ^2.6.1
laminas/laminas-diactoros ^2.4.1
laminas/laminas-httphandlerrunner ^1.2.0
laminas/laminas-stratigility ^3.2.2
league/flysystem ^1.0.11
matthiasmullie/minify ^1.3
middlewares/base-path ^2.0.1
middlewares/base-path-router ^2.0.1
middlewares/request-handler ^2.0.1
monolog/monolog ^1.16.0
nesbot/carbon ^2.0
nikic/fast-route ^0.6
php >=7.3
psr/http-message ^1.0
psr/http-server-handler ^1.0
psr/http-server-middleware ^1.0
s9e/text-formatter ^2.3.6
symfony/config ^5.2.2
symfony/console ^5.2.2
symfony/event-dispatcher ^5.2.2
symfony/mime ^5.2.0
symfony/polyfill-intl-messageformatter ^1.22.0
symfony/translation ^5.1.5
symfony/yaml ^5.2.2
tobscure/json-api ^0.3.0
wikimedia/less.php ^3.0

requires (dev)
flarum/testing 1.0@dev
`

**Comment by connor557** [comment]
Altering the database tables made the website work as normal again,  thanks for all the help everyone
