### ISSUE TITLE
Vagrant provision fails (?) with PHP exception

### ISSUE THREAD

**Issue by zaksoup** [flarum/core#556]
```
==> Vaprobash: PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class Flarum\Console\GenerateMigrationCommand does not exist' in /vagrant/flarum/vendor/illuminate/container/Container.php:736
==> Vaprobash: Stack trace:
==> Vaprobash: #0 /vagrant/flarum/vendor/illuminate/container/Container.php(736): ReflectionClass->__construct('Flarum\\Console\\...')
==> Vaprobash: #1 /vagrant/flarum/vendor/illuminate/container/Container.php(626): Illuminate\Container\Container->build('Flarum\\Console\\...', Array)
==> Vaprobash: #2 /vagrant/flarum/core/src/Core/Application.php(663): Illuminate\Container\Container->make('Flarum\\Console\\...', Array)
==> Vaprobash: #3 /vagrant/flarum/flarum(26): Flarum\Core\Application->make('Flarum\\Console\\...')
==> Vaprobash: #4 {main}
==> Vaprobash:   thrown in /vagrant/flarum/vendor/illuminate/container/Container.php on line 736
```

This isn't actually failing, just showing up at the very end of what otherwise appears to be a successful vagrant provision without error. It seems, however, that this is indicative of a larger issue with loading dependencies as when the page attempts to load fonts it gets 500s from the server. I am by no means an expert in PHP so I appreciate your patience as I get started here.

for your sanity I've posted the html of the error here: https://dl.dropboxusercontent.com/u/911818/flarum/debug.html

```html
<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught exception 'ReflectionException' with message 'Class Flarum\Api\Middleware\FakeHttpMethods does not exist' in /vagrant/flarum/vendor/illuminate/container/Container.php on line <i>736</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> ReflectionException: Class Flarum\Api\Middleware\FakeHttpMethods does not exist in /vagrant/flarum/vendor/illuminate/container/Container.php on line <i>736</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0031</td><td bgcolor='#eeeeec' align='right'>128792</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/vagrant/api.php' bgcolor='#eeeeec'>.../api.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.1256</td><td bgcolor='#eeeeec' align='right'>1522192</td><td bgcolor='#eeeeec'>Flarum\Core\Application->make(  )</td><td title='/vagrant/api.php' bgcolor='#eeeeec'>.../api.php<b>:</b>24</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.1256</td><td bgcolor='#eeeeec' align='right'>1522268</td><td bgcolor='#eeeeec'>Illuminate\Container\Container->make(  )</td><td title='/vagrant/flarum/core/src/Core/Application.php' bgcolor='#eeeeec'>.../Application.php<b>:</b>663</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.1256</td><td bgcolor='#eeeeec' align='right'>1522268</td><td bgcolor='#eeeeec'>Illuminate\Container\Container->build(  )</td><td title='/vagrant/flarum/vendor/illuminate/container/Container.php' bgcolor='#eeeeec'>.../Container.php<b>:</b>626</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.1256</td><td bgcolor='#eeeeec' align='right'>1522384</td><td bgcolor='#eeeeec'><a href='http://www.php.net/ReflectionClass.construct' target='_new'>__construct</a>
(  )</td><td title='/vagrant/flarum/vendor/illuminate/container/Container.php' bgcolor='#eeeeec'>.../Container.php<b>:</b>736</td></tr>
<tr><th align='left' colspan='5' bgcolor='#e9b96e'>Variables in local scope (#4)</th></tr>
<tr><td colspan='2' align='right' bgcolor='#eeeeec' valign='top'><pre>$concrete&nbsp;=</pre></td><td colspan='3' bgcolor='#eeeeec'><pre class='xdebug-var-dump' dir='ltr'><small>string</small> <font color='#cc0000'>'Flarum\Api\Middleware\FakeHttpMethods'</font> <i>(length=37)</i>
</pre></td></tr>
<tr><td colspan='2' align='right' bgcolor='#eeeeec' valign='top'><pre>$constructor&nbsp;=</pre></td><td colspan='3' bgcolor='#eeeeec' valign='top'><i>Undefined</i></td></tr>
<tr><td colspan='2' align='right' bgcolor='#eeeeec' valign='top'><pre>$dependencies&nbsp;=</pre></td><td colspan='3' bgcolor='#eeeeec' valign='top'><i>Undefined</i></td></tr>
<tr><td colspan='2' align='right' bgcolor='#eeeeec' valign='top'><pre>$instances&nbsp;=</pre></td><td colspan='3' bgcolor='#eeeeec' valign='top'><i>Undefined</i></td></tr>
<tr><td colspan='2' align='right' bgcolor='#eeeeec' valign='top'><pre>$message&nbsp;=</pre></td><td colspan='3' bgcolor='#eeeeec' valign='top'><i>Undefined</i></td></tr>
<tr><td colspan='2' align='right' bgcolor='#eeeeec' valign='top'><pre>$parameters&nbsp;=</pre></td><td colspan='3' bgcolor='#eeeeec'><pre class='xdebug-var-dump' dir='ltr'>
<b>array</b> <i>(size=0)</i>
  <i><font color='#888a85'>empty</font></i>
</pre></td></tr>
<tr><td colspan='2' align='right' bgcolor='#eeeeec' valign='top'><pre>$reflector&nbsp;=</pre></td><td colspan='3' bgcolor='#eeeeec' valign='top'><i>Undefined</i></td></tr>
</table></font>
```

**Comment by tobscure** [comment]
Can you make sure you have the latest commit pulled in for flarum/core?

**Comment by zaksoup** [comment]
I've pulled in the latest commit from flarum/core and vagrant up/provision succeed.

Fonts still don't load correctly and now instead of actual text I see "core.placeholder" text everywhere.

**Comment by Mecvak** [comment]
>  instead of actual text I see "core.placeholder" text everywhere. 

I can [confirm](http://bleedingflarum.xyzz.work/) - however I do not think it is related to the vagrant provision as I am using a build script (unrelated to vagrant) and core.* recently showed up in a commit.
So it needs to be fixed at some point but I believe this issue is solved.

**Comment by zaksoup** [comment]
I agree @Mecvak, the original vagrant issue is solved and this thread can be closed.

**Comment by franzliedke** [comment]
You need to install the flarum/english extension, that was recently extracted from core. 

Fonts: true, we still need to make asset publication work on the Vagrant environment. There is a ticket, though, so we won't forget it, don't worry.
