### ISSUE TITLE
Beta 2 creating a new discussion

### ISSUE THREAD

**Issue by hcgtv** [flarum/core#570]
Hello Flarum!

Just installed v0.1.0 Beta 2 on VirtualBox:
Debian GNU/Linux 8.1 “Jessie”, Apache 2.4.10, MySQL 5.5.44, PHP 5.6.13

The install went fine, but when I try to add a new discussion, I get a popup saying:
Oops! Something went wrong on the server. Please reload the page and try again.

This is from the PHP error log:
[02-Oct-2015 11:58:14 America/New_York] PHP Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0
[02-Oct-2015 15:58:15 UTC] PHP Fatal error: Uncaught exception 'RuntimeException' with message 'Unable to emit response; headers already sent' in /home/www/zendstudio/flarum/flarum/vendor/zendframework/zend-diactoros/src/Response/SapiEmitter.php:29
Stack trace:
#0 /home/www/zendstudio/flarum/flarum/vendor/zendframework/zend-diactoros/src/Server.php(170): Zend\Diactoros\Response\SapiEmitter->emit(Object(Zend\Diactoros\Response\JsonResponse), 2)
#1 /home/www/zendstudio/flarum/api.php(42): Zend\Diactoros\Server->listen()
#2 {main}
thrown in /home/www/zendstudio/flarum/flarum/vendor/zendframework/zend-diactoros/src/Response/SapiEmitter.php on line 29

Looking good, time to kick the tires, but it don't want to start 😟

**Comment by tobscure** [comment]
Try setting `always_populate_raw_post_data` to `-1` in your php.ini.
