### ISSUE TITLE
API: Class UpdateForumController does not exist

### ISSUE THREAD

**Issue by KennethWussmann** [flarum/core#725]
Hey, 
I'm unsure about the origin of this error message. It may be my fault but it says a class is missing so I would like to ask you.

I would like to create a Flarum API-Wrapper. Now I tried to save the forum informations using:

```Java
try {
	HttpResponse<JsonNode> response = Unirest.patch(jflarum.getFlarumUrl() + "/api/forum")
		.body("{\"op\": \"replace\",\"path\": \"/data/attributes/title\",\"value\": \"Test\"}")
		.asJson();
	System.out.println(response.getBody().toString());
} catch (UnirestException e) {
	e.printStackTrace();
}
```
Notice that the Auth-Token already is set in the header.

So I'm trying to patch using JSON: 
```JavaScript
{
  "op": "replace",
  "path": "/data/attributes/title",
  "value": "Test"
}
```

Now I'm getting this error:

```
{"errors": [{
      "detail": "exception 'ReflectionException' with message 'Class Flarum\\Api\\Controller\\UpdateForumController does not exist' in /var/customers/webs/Kenneth/flarum/vendor/illuminate/container/Container.php:741
Stack trace:
#0 /var/customers/webs/Kenneth/flarum/vendor/illuminate/container/Container.php(741): ReflectionClass->__construct('Flarum\\\\Api\\\\Cont...')
#1 /var/customers/webs/Kenneth/flarum/vendor/illuminate/container/Container.php(631): Illuminate\\Container\\Container->build('Flarum\\\\Api\\\\Cont...', Array)
#2 /var/customers/webs/Kenneth/flarum/vendor/flarum/core/src/Foundation/Application.php(484): Illuminate\\Container\\Container->make('Flarum\\\\Api\\\\Cont...', Array)
#3 /var/customers/webs/Kenneth/flarum/vendor/flarum/core/src/Http/GenerateRouteHandlerTrait.php(26): Flarum\\Foundation\\Application->make('Flarum\\\\Api\\\\Cont...')
#4 /var/customers/webs/Kenneth/flarum/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(67): Flarum\\Api\\ApiServiceProvider->Flarum\\Http\\{closure}(Object(Zend\\Stratigility\\Http\\Request), Array)
#5 [internal function]: Flarum\\Http\\Middleware\\DispatchRoute->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))
#6 /var/customers/webs/Kenneth/flarum/vendor/zendframework/zend-stratigility/src/Dispatch.php(81): call_user_func(Object(Flarum\\Http\\Middleware\\DispatchRoute), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))
#7 /var/customers/webs/Kenneth/flarum/vendor/zendframework/zend-stratigility/src/Next.php(113): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))
#8 /var/customers/webs/Kenneth/flarum/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(32): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))
#9 [internal function]: Flarum\\Api\\Middleware\\FakeHttpMethods->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))
#10 /var/customers/webs/Kenneth/flarum/vendor/zendframework/zend-stratigility/src/Dispatch.php(81): call_user_func(Object(Flarum\\Api\\Middleware\\FakeHttpMethods), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))
#11 /var/customers/webs/Kenneth/flarum/vendor/zendframework/zend-stratigility/src/Next.php(113): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))
#12 /var/customers/webs/Kenneth/flarum/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(30): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))
#13 [internal function]: Flarum\\Http\\Middleware\\ParseJsonBody->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))
#14 /var/customers/webs/Kenneth/flarum/vendor/zendframework/zend-stratigility/src/Dispatch.php(81): call_user_func(Object(Flarum\\Http\\Middleware\\ParseJsonBody), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))
#15 /var/customers/webs/Kenneth/flarum/vendor/zendframework/zend-stratigility/src/Next.php(113): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))
#16 /var/customers/webs/Kenneth/flarum/vendor/flarum/core/src/Api/Middleware/AuthenticateWithHeader.php(50): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))
#17 [internal function]: Flarum\\Api\\Middleware\\AuthenticateWithHeader->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))
#18 /var/customers/webs/Kenneth/flarum/vendor/zendframework/zend-stratigility/src/Dispatch.php(81): call_user_func(Object(Flarum\\Api\\Middleware\\AuthenticateWithHeader), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))
#19 /var/customers/webs/Kenneth/flarum/vendor/zendframework/zend-stratigility/src/Next.php(113): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))
#20 /var/customers/webs/Kenneth/flarum/vendor/flarum/core/src/Http/Middleware/AuthenticateWithCookie.php(42): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))
#21 [internal function]: Flarum\\Http\\Middleware\\AuthenticateWithCookie->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))
#22 /var/customers/webs/Kenneth/flarum/vendor/zendframework/zend-stratigility/src/Dispatch.php(81): call_user_func(Object(Flarum\\Http\\Middleware\\AuthenticateWithCookie), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))
#23 /var/customers/webs/Kenneth/flarum/vendor/zendframework/zend-stratigility/src/Next.php(113): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))
#24 /var/customers/webs/Kenneth/flarum/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(75): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))
#25 /var/customers/webs/Kenneth/flarum/vendor/zendframework/zend-diactoros/src/Server.php(166): Zend\\Stratigility\\MiddlewarePipe->__invoke(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Diactoros\\Response), NULL)
#26 /var/customers/webs/Kenneth/flarum/vendor/flarum/core/src/Http/AbstractServer.php(33): Zend\\Diactoros\\Server->listen()
#27 /var/customers/webs/Kenneth/flarum/api.php(16): Flarum\\Http\\AbstractServer->listen()
#28 {main}",
      "title": "Internal server error",
      "code": 500
    }]}
```

I've installed Flarum `0.1.0-beta.4`. Completly fresh Flarum instance.

Thanks for your help.

**Comment by Luceos** [comment]
First off, I'd use dev-master. Secondly what are you trying to accomplish with the api request?

**Comment by KennethWussmann** [comment]
Thanks, I'll try out the dev-master later. 
I would like to set the forum title to `Test` using the `/api/forum` endpoint.

**Comment by franzliedke** [comment]
Hmm, that's indeed a bug. Not sure where the class went...

@tobscure Can you enlighten us? Looks like it disappeared during a very large commit.

**Comment by tobscure** [comment]
We don't support a PATCH on /api/forum – that route should be removed. Rather, settings can be updated directly using the POST /api/settings endpoint, which accepts a simple key-value object of settings to update.

Also note that none of our PATCH endpoints support the JSON PATCH format. They should be used in accordance with the [JSON-API spec](http://jsonapi.org/format/#crud-updating).

**Comment by KennethWussmann** [comment]
@tobscure Okay, thanks for your help. 
Nevertheless I don't get it working.
I tried the following requests: 

* Simple `POST /api/settings` with form-data `title=New Title`
* `POST /api/settings` with:
```JavaScript
{  
   "title" : "New Title"
}
```
* `POST /api/settings` with:
```JavaScript
{
  "data": {
    "type": "forums",
    "id": "1",
    "attributes": {
      "title": "New Title"
    }
  }
}
```
* `POST /api/settings` with:
```JavaScript
{
  "data": {
    "attributes": {
      "title": "New Title"
    }
  }
}
```
I also tried to modify `description`, same result. 
The JSON-Requests also had the header `Content-Type` set to `application/json`.

But I always get: 
```JavaScript
{
  "errors": [
    []
  ]
}
```
No errors in the array but the title is always the old one. 

Thanks.

**Comment by tobscure** [comment]
Your second attempt is in the correct format, but the key must match the one in the `settings` database table (I think it's "forum_title").

**Comment by KennethWussmann** [comment]
Ah, the key in the database. Thought it would be the keys from `/api/forum`.

Thanks for your help. Feel free to close if you want to.

**Comment by tobscure** [comment]
No worries! I'll leave open because we need to remove that dud PATCH /api/forum route.
