### ISSUE TITLE
when go to flarum by guest, not show discussions

### ISSUE THREAD

**Issue by zairl23** [flarum/core#84]
I am sure i pull the latest the codes, just throw the errors:

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users_groups.guest_id' in 'where clause' (SQL: select `id` from `groups` inner join `users_groups` on `groups`.`id` = `users_groups`.`group_id` where `users_groups`.`guest_id` is null)' in /vagrant/system/vendor/laravel/framework/src/Illuminate/Database/Connection.php:624
Stack trace:
#0 /vagrant/system/vendor/laravel/framework/src/Illuminate/Database/Connection.php(580): Illuminate\Database\Connection->runQueryCallback('select `id` fro...', Array, Object(Closure))
#1 /vagrant/system/vendor/laravel/framework/src/Illuminate/Database/Connection.php(297): Illuminate\Database\Connection->run('select `id` fro...', Array, Object(Closure))
#2 /vagrant/system/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1377): Illuminate\Database\Connection->select('select `id` fro...', Array, true)
#3 /vagrant/system/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1367): Illuminate\Database\Query\Builder->runSelect()
#4 /vagrant/system/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1354): Illuminate\Database\Query\Builder->getFresh(Array)
#5 /vagrant/system/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1504): Illuminate\Database\Query\Builder->get(Array)
#6 /vagrant/system/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(221): Illuminate\Database\Query\Builder->lists('id', NULL)
#7 [internal function]: Illuminate\Database\Eloquent\Builder->lists('id')
#8 /vagrant/system/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(283): call_user_func_array(Array, Array)
#9 /vagrant/system/core/src/Core/Models/User.php(453): Illuminate\Database\Eloquent\Relations\Relation->__call('lists', Array)
#10 /vagrant/system/core/src/Core/Models/User.php(453): Illuminate\Database\Eloquent\Relations\BelongsToMany->lists('id')
#11 /vagrant/system/core/src/Core/Models/User.php(323): Flarum\Core\Models\User->permissions()
#12 /vagrant/system/core/src/Core/CoreServiceProvider.php(196): Flarum\Core\Models\User->hasPermission('discussion.view')
#13 /vagrant/system/core/vendor/tobscure/permissible/src/Permissible.php(96): Flarum\Core\CoreServiceProvider->Flarum\Core\{closure}(Object(Tobscure\Permissible\Condition\Builder), Object(Flarum\Core\Models\Guest), 'view')
#14 /vagrant/system/core/vendor/tobscure/permissible/src/Permissible.php(65): Flarum\Core\Models\Discussion->constructConditions(Array, Object(Flarum\Core\Models\Guest), 'view', 'or')
#15 /vagrant/system/core/vendor/tobscure/permissible/src/Permissible.php(112): Flarum\Core\Models\Discussion->getConditions(Object(Flarum\Core\Models\Guest), 'view')
#16 /vagrant/system/core/vendor/tobscure/permissible/src/Permissible.php(54): Flarum\Core\Models\Discussion->getPermissionWheres(Object(Flarum\Core\Models\Guest), 'view')
#17 [internal function]: Flarum\Core\Models\Discussion->scopeWhereCan(Object(Illuminate\Database\Eloquent\Builder), Object(Flarum\Core\Models\Guest), 'view')
#18 /vagrant/system/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(816): call_user_func_array(Array, Array)
#19 /vagrant/system/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(930): Illuminate\Database\Eloquent\Builder->callScope('scopeWhereCan', Array)
#20 /vagrant/system/core/src/Core/Search/Discussions/DiscussionSearcher.php(62): Illuminate\Database\Eloquent\Builder->__call('whereCan', Array)
#21 /vagrant/system/core/src/Core/Search/Discussions/DiscussionSearcher.php(62): Illuminate\Database\Eloquent\Builder->whereCan(Object(Flarum\Core\Models\Guest), 'view')
#22 /vagrant/system/core/src/Api/Actions/Discussions/IndexAction.php(73): Flarum\Core\Search\Discussions\DiscussionSearcher->search(Object(Flarum\Core\Search\Discussions\DiscussionSearchCriteria), 20, 0, Array)
#23 /vagrant/system/core/src/Api/Actions/SerializeAction.php(76): Flarum\Api\Actions\Discussions\IndexAction->data(Object(Flarum\Api\JsonApiRequest), Object(Flarum\Api\JsonApiResponse))
#24 /vagrant/system/core/src/Api/routes.php(22): Flarum\Api\Actions\SerializeAction->handle(Object(Flarum\Api\Request))
#25 [internal function]: Flarum\Api\ApiServiceProvider->{closure}()
#26 /vagrant/system/vendor/laravel/framework/src/Illuminate/Routing/Route.php(157): call_user_func_array(Object(Closure), Array)
#27 /vagrant/system/vendor/laravel/framework/src/Illuminate/Routing/Route.php(129): Illuminate\Routing\Route->runCallable(Object(Illuminate\Http\Request))
#28 /vagrant/system/vendor/laravel/framework/src/Illuminate/Routing/Router.php(701): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#29 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /vagrant/system/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#31 /vagrant/system/core/src/Api/Middleware/LoginWithHeader.php(31): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /vagrant/system/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Flarum\Api\Middleware\LoginWithHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /vagrant/system/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 /vagrant/system/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#36 /vagrant/system/vendor/laravel/framework/src/Illuminate/Routing/Router.php(670): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#37 /vagrant/system/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#38 /vagrant/system/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(214): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#40 /vagrant/system/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#41 /vagrant/system/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /vagrant/system/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /vagrant/system/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /vagrant/system/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /vagrant/system/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /vagrant/system/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /vagrant/system/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /vagrant/system/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /vagrant/system/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /vagrant/system/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /vagrant/system/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#53 /vagrant/system/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(115): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#54 /vagrant/system/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#55 /vagrant/index.php(9): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#56 {main}  

And the permissions table is:

+----------+-----------------------+
| group_id | permission            |
+----------+-----------------------+
|        2 | forum.register        |
|        2 | forum.view            |
|        3 | discussion.editOwn    |
|        3 | discussion.reply      |
|        3 | forum.startDiscussion |
|        3 | post.editOwn          |
|        4 | discussion.delete     |
|        4 | discussion.edit       |
|        4 | post.delete           |
|        4 | post.edit             |
|        4 | user.suspend          |
+----------+-----------------------+

any wrong with that??

**Comment by zairl23** [comment]
But when i login in, everything works fine!
